### ISSUE TITLE
How to calculate MultiLevelPartition

### ISSUE THREAD

**Issue by samuelnygaard** [michaelwegner/CRP#1]
Hi Michael

We are trying to use our fine implementation of CRP for our semester project at Aalborg University.
We have got i all to work but we can't figure out how make a MultiLevelPartition using KaHIP and Buffoon, (Christian Schulz have provided KaHip with Buffoon extension) we have tried making a single level partition using both kaffpa and buffoon, but how do we make the mlp file from the metis graph file?
As for a we can read from the KaHIP documentation kaffpa makes the MultiLevelPartition and we can supply an existing partition (e.g. from Buffoon) to kaffpa, but how?

I hope you can help us. Best regards Samuel.

**Comment by michaelwegner** [comment]
Hi Samuel,

take a look at the documentation of MultiLevelPartition.h. The partitioner should output some sort of partition file that tells you in which partition each vertex is. This information can then be stored in the MultiLevelPartition data structure using the provided methods. You have to specify the partition (aka cell) for each vertex on every level. So for getting multiple levels you have to recursively compute a partitioning of each partition of the next higher level and store the returned information in MultiLevelPartition. 

Cheers,
Michael
